[package]
name = "pawn_fight"
version = "0.0.1"
authors = ["Shinski"]
edition = "2018"

[dependencies]
conrod_core = "0.73.0"
conrod_piston = "0.73.0"
itertools = "0.10.0"
piston_window = "0.114.0"
rand = "0.8.3"
