name: Rust

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prep
      run: sudo apt-get update && sudo apt-get install libxcb-shape0 libxcb-xfixes0 -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
